bracketSpacing: true
printWidth: 200
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"

overrides:
  - files: "*.sol"
    options:
      compiler: "0.8.18"
      tabWidth: 4
      printWidth: 99
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
